<?php
$global_promotion_enabled = true;
$global_promotion_override_usp = true;
$sitewide_type = 'text_bar';
$usp_promo_text_class = '';
$sitewide_text_type = '3d_text_1';
$base_colour = '#CD0000';
$gradient_colour = '#f13e4f';
$usp_promo_text = 'SALE';
$usp_promo_subtext = 'UP TO 75% OFF! SAVE BIG ON TIES, BOW TIES, POCKET SQUARES AND MORE!';
$promo_button_text = 'SHOP NOW';
$promo_button_link = '/sale';
$center_text_colour = '#fff';


if($sitewide_text_type == '3d_text_1'){

    $usp_promo_text_class = '
    margin: 0;
    flex: 0 1 auto;
    padding: 0;
    margin-left: 0px;
    color: #fff;
    text-align: left;
    font-size: 48px;
    font-weight: normal;
    padding: 6px 10px 10px 20px;
    line-height: 100%;
    text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,0.1), 0 0 5px rgba(0,0,0,0.1), 0 1px 3px rgba(0,0,0,0.3), 0 3px 5px rgba(0,0,0,0.2), 0 5px 10px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.2), 0 20px 20px rgba(0,0,0,0.15);
    -webkit-transition: .2s all linear;';

}

?>
  <style>
    @media (max-width: 767px) {
      #promo_center_text {
        display: none;
      }
      .promo_link{
        padding-right:15px !important;
      }
      .promo_brand{
        padding-left:15px !important;
      }
    }
    .nav-sections{
      margin-bottom:0px;
    }
  </style>

<?php
if($sitewide_type == 'text_bar'){
    ?>
  <div id="usp_text_bar" style="margin-bottom:25px;
      background-color: <?php echo $base_colour; ?>;
      background-image: -webkit-gradient(linear, 0 0, 0 100%, from(<?php echo $base_colour; ?>), to(<?php echo $gradient_colour; ?>));
      width: 100%;">

    <div style="margin-left: auto;margin-right: auto; display: flex;align-items: center;justify-content: center;max-width: 1280px;">


      <div class="promo_brand" style="<?php echo $usp_promo_text_class; ?>"><?php echo $usp_promo_text; ?></div>

      <p style="margin: 0;padding: 0;font-weight: normal;text-transform: uppercase;text-align: left;letter-spacing: 0.2px;flex: 1 1 auto;color: <?php echo $center_text_colour; ?>;padding: 0 30px;text-align: center;" id="promo_center_text">
          <?php echo $usp_promo_subtext; ?>
      </p>

      <a class="promo_link" href="<?php echo $promo_button_link; ?>" style="cursor:pointer;padding-right:20px; color: <?php echo $center_text_colour; ?>;">
        <span style="font-weight:500;border: 1px solid #f7f7f7;border-radius:3px;padding:10px;width: auto;display: inline-block;margin: 15px 0px;min-width: 100px;text-align: center;"><?php echo $promo_button_text; ?></span></a></div></div>

    <?php

}
if($sitewide_type == 'usp_bar'){

  ?>
  <style>
    #subheading-bar {
      background-color: #f6f8fb;
      padding: 13px 0;
      margin-bottom:20px;
    }
    #subheading-inner {
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .sub-hdr-item {
      flex: 0 1 auto;
      width: 25%;
      padding-left: 5px;
      height: 36px;
    }
    @media screen and (min-width: 1470px){
      .sub-hdr-item {
        height: 42px;
        padding-left: 0;
      }
    }
    .sub-hdr-item>a {
      display: block;
      height: 100%;
    }
    .sub-hdr-item .sh-inner {
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .sub-hdr-cta-ico {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 35px;
      margin: 0 4px;
    }
    @media screen and (min-width: 1470px){
      .sub-hdr-cta-ico, .sub-hdr-cta-ico.sub-hdr-manu-ico {
        margin: 0 10px;
      }
    }
    .sub-hdr-hdr-text {
      color: #0e1936;
      line-height: 1.6;
      font-size: 14px;
      text-transform: uppercase;
      font-weight: 400;
    }
    .sub-hdr-text {
      color: #8b8f9a;
    }
  </style>
  <?php
  ?>
  <div id="subheading-bar">
    <div id="subheading-inner" class="container-ev">
      <div id="sh-i-block1" class="sub-hdr-item">
        <a aria-label="Delivery" href="/help-and-advice/delivery-information">
          <div class="sh-inner">
            <div class="sub-hdr-cta-ico sub-hdr-del-ico"><i class="sub-hdr-delivery-ico"></i></div>
            <div class="sub-hdr-right">
              <div class="sub-hdr-hdr-text">Free Shipping</div>
              <div class="sub-hdr-text">Available to UK Mainland*</div>
            </div>
          </div>
        </a>
      </div>
      <div id="sh-i-block2" class="sub-hdr-item hidden-xs">
        <a aria-label="Manufacturers Guarantee" href="/manufacturers-guarantee">
          <div class="sh-inner">
            <div class="sub-hdr-cta-ico sub-hdr-manu-ico"><i class="sub-hdr-rosette-ico"></i></div>
            <div class="sub-hdr-right">
              <div class="sub-hdr-hdr-text">Manufacturer's Guarantee</div>
              <div class="sub-hdr-text">5 Years for Total Peace of Mind</div>
            </div>
          </div>
        </a>
      </div>
      <div id="sh-i-block3" class="sub-hdr-item hidden-xs">
        <a aria-label="Customer Reviews" href="/customer-reviews">
          <div class="sh-inner">
            <div class="sub-hdr-cta-ico sub-hdr-trophy-ico"><i class="sub-hdr-award-ico"></i></div>
            <div class="sub-hdr-right">
              <div class="sub-hdr-hdr-feefo"></div>
              <div class="sub-hdr-text">Rated Excellent - <strong>4552</strong> <span class="hidden-md"> Customer </span>Reviews</div>
            </div>
          </div>
        </a>
      </div>
      <div id="sh-i-block4" class="sub-hdr-item hidden-xs hidden-sm">
        <a aria-label="About Us" href="/who-we-are">
          <div class="sh-inner">
            <div class="sub-hdr-cta-ico sub-hdr-flag-ico"><i class="sub-hdr-uk-ico"></i></div>
            <div class="sub-hdr-right">
              <div class="sub-hdr-hdr-text">Made in Britain</div>
              <div class="sub-hdr-text">Mattresses &amp; Divans Made in the UK</div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>


    <?php

}
else{


    $global_promotion_override_usp_custom2 = '



<div class="site-widepromotions-usp" style="background-color: #86c2c2;">
  <div class="swp-inner container">
    <div class="swp-left">
      <img class=" lazyload" src="/media/loader.png" data-src="/media/THINBANNERcomponent1.png">
    </div>

    <div class="swp-center" style="text-align: center;">
      <img class="lazyload" src="/media/loader.png" data-src="/media/thinbannerchangecomponent2.png">
    </div>

    <div class="swp-right">
      <img class=" lazyload" src="/media/loader.png" data-src="/media/thinbannerchangecomponent3.png">
    </div>
  </div>
</div>

';


    $sitewide_enable = false;

    $global_promotion_enabled = false;
    if($sitewide_enable && $global_promotion_enabled){

        $global_promotion_listing_text = 'text';
        $global_promotion_background_colour = '#fff';
        $global_promotion_font_colour = '#fff';
        $global_blacklist = explode(',', '');
        $global_blacklist = array_flip($global_blacklist);

        $global_promotion_countdown_pp_enable = true;
        $global_promotion_countdown_time = '30/01/2020 10:00:00';

        $global_promotion_countdown_list_background_colour = '#fff';
        $global_promotion_countdown_list_font_colour = '#fff';


        $global_promotion_countdown_banner_image = '';
        $global_promotion_countdown_banner_image_bkg = '#fff';
        $global_promotion_countdown_pp_background_colour = '#fff';




        $sitewide_background_colour = '';
        $sitewide_image = '';
        $main_text = '';

        $pill_colour = '';
        $pill_text = '';
        $pill_text_colour = '';

        $sub_header_main_colour = '';
        $sub_header_subtext_colour = '';
        $sub_header_invert = '';
        $sitewide_link = '';

        $sitewide_bkg_image = '';
        $sitewide_custom_block = '';


        $_gpsku = '';

        $global_promotion = false;

        if ($_gpsku == '') {

            $global_promotion = true;

        } else {
            $global_promotion_skus = explode(',', $_gpsku);
            $global_promotion_skus = array_flip($global_promotion_skus);
        }



        $global_promo_this_product = true;
        if ($global_promotion_enabled) {
            ?>
          <style>

            #subheading-inner {
              display: flex;
              align-items: center;
              justify-content: center;
            }



            #subheading-bar {
              background-color: #f6f8fb;
              padding: 0;
            }
            .slider-wrap {
              position:         relative;
              height:           57px;

              background-size:  cover;
              display:          flex;
              align-items:      center;
              justify-content:  flex-end;
            }

            #countdown_timer {
              height:          100%;
              display:         flex;
              align-items:     center;
              justify-content: flex-end;
            }


            ul#countdown_timer li:first-child {
              margin-left: 0px;
            }

            ul#countdown_timer li span {
              font-size:   19px;
              padding-top: 0;
              margin-top:  0;
            }

            ul#countdown_timer li p {
              margin:         0;
              font-size:      13px;
              padding:        0;
              text-transform: uppercase;
            }

            .count-dwn-btn {
              background:     yellow;
              display:        block;
              width:          100%;
              text-align:     center;
              text-transform: uppercase;
              color:          #000000;
              font-size:      25px;
              margin:         5px 0 5px 0;
              margin-top:     12px;
              padding:        10px;
            }

            .elements {
              width: 100%;
            }

            .inner-elements {
              display:    flex;
              width:      100%;
              text-align: right;
              padding: 10px 0px 0px 0px;
            }

            .the-sale-text-icon {
              flex:       0 1 auto;
              order:      1;
              align-self: flex-start;
              width:      40%;
              margin-right:7px;
            }

            .the-sale-text-icon img {
              height: 45px;
              width:  100%;
            }

            .countdown-timer-outer {
              flex:         0 1 auto;
              order:        2;
              margin-right: 3px;
              width:        60%;
            }
            .elements {
              width: 100%;
            }
            .inner-elements {
              display: flex;
              width: 100%;
              text-align: right;
            }
            .the-sale-text-icon {
              flex: 0 1 auto;
              order: 1;
              align-self: center;
              width: 40%;
            }
            .the-sale-text-icon img {
              height: 45px;
              width: 100%;
              padding-left: 15px;
            }
            .countdown-timer-outer {
              flex: 0 1 auto;
              order: 2;
              margin-right: 3px;
              width: 60%;
            }

            @media only screen and (max-width: 480px) {
              ul#countdown_timer li {
                font-size: 11px;
              }

              ul#countdown_timer li span {
                font-size: 10px;
              }

              ul#countdown_timer li p {
                font-size: 9px;
              }

              ul#countdown_timer li {
                width: 46px !important;
              }

              .the-sale-text-icon img {
                height: 35px;
                width:  100px;
              }

              .the-sale-text-icon {
                width: 37%
              }

              .countdown-timer-outer {
                width: 63%;
              }
            }
            @media (max-width: 1200px) and (min-width: 992px) {
              div#sh-i-block1 {

                display: none;
              }
            }
            @media (max-width: 1169.98px) and (min-width: 992px) {
              div#sh-i-block1 {

                display: none;
              }
              ul#countdown_timer li {
                font-size: 12px;
              }



              ul#countdown_timer li p {
                font-size: 12px;
              }

              ul#countdown_timer li {
                width: 57px !important;
              }
            }

            @media (max-width: 991.98px) and (min-width: 768px) {

              ul#countdown_timer li {
                font-size: 12px;
              }


              ul#countdown_timer li p {
                font-size: 10px;
              }

              ul#countdown_timer li {
                width: 57px !important;
              }

            }
            ul#countdown_timer li {
              text-align: center;
              font-size: 32px;
              flex: 0 1 auto;
              display: inline-block;
              align-items: stretch;
              width: 66px;
              height: auto;

              vertical-align: top;
              color: black;
              border-radius: -15px;
              padding: 0;
              background-color: transparent !important;
              margin: 0 2px;
              line-height: 20px;
              color: white !important;
              border: 2px solid #fff !important;
              border-radius: 10px !important;
            }
            ul#countdown_timer li{

              opacity:1 !important;
            }
            .slider-wrap {
              border-radius: 10px;
              height: 57px;
              background-color: <?php echo $sitewide_background_colour; ?> !important;
              height: auto;
            }

            @media only screen and (max-width: 480px){
              .inner-elements {
                flex-wrap: wrap;
              }
              .the-sale-text-icon img {
                height: auto;
                width: 90%;
                margin: 0 auto;
                display: block;
              }

              .the-sale-text-icon {
                width: 100%;
                margin: 0 auto;
              }
              ul#countdown_timer {
                display: block;
                text-align: center;
              }
              .slider-wrap{
                border-radius: 0px;
              }
              ul#countdown_timer li {
                opacity: 1;

                width: 24% !important;
                margin: 0px !important;
              }
              ul#countdown_timer li span {
                font-size: 17px;
              }
              .countdown-timer-outer {
                width: 100%;
                margin-top: 15px;
                margin-bottom: 0;
                margin-left: 0px !important;
                margin-right: 0px !important;
              }
            }
            #headwrap .slider-wrap{

              border-radius:0px;
            }
            .the-sale-text-icon img {

              float: left;
            }
            .the-sale-text-icon img {
              height: 45px;
              width: auto !important;
              padding-left: 15px;
            }
            div#subheading-bar .slider-wrap{
              display:block !important;

            }
            div#subheading-bar {

              background-color: <?php echo $sitewide_background_colour; ?> !important;
              padding-top: 0;
            }
            div#sh-i-block1 {
              padding-top: 0px;
            }
            div#sh-i-block2 {
              padding-top: 0px;
            }
            div#sh-i-block3 {
              padding-top: 0px;
            }
            .sub-hdr-hdr-text {
              color: <?php echo $sub_header_subtext_colour; ?>;
            }
            .sub-hdr-text {
              color: <?php echo $sub_header_main_colour; ?>;
            }
            @media screen and (min-width: 1470px){
              .sub-hdr-item {
                height: 53px;
                padding-left: 0;
              }
            }

            <?php if($sub_header_invert){ ?>
            .sub-hdr-hdr-feefo, .sub-hdr-rosette-ico, .sub-hdr-award-ico, .sub-hdr-delivery-ico {

              filter: brightness(1);
              filter: brightness(0) invert(1);
            }

            <?php } ?>
            #sh-i-block4{width: 40%;    padding-top: 0px;}
            #subheading-bar #countdown_timer li span {
              line-height: 20px !important;
            }
            @media screen and (max-width: 991.98px){
              div#subheading-bar .slider-wrap{

                margin-bottom:0px !important;
              }
              #subheading-bar {
                display: block;
              }

              #subheading-bar .the-sale-text-icon {
                text-align: left;
              }
              #subheading-bar div#sh-i-block1 {
                display:none;
              }
              #subheading-bar div#sh-i-block2 {
                display:none;
              }
              #subheading-bar div#sh-i-block3 {
                display:none;
              }
              #subheading-bar .sub-hdr-item {
                flex: 0 1 auto;
                width: 25%;
                padding-left: 5px;
                height: 56px;
              }
              #subheading-bar #sh-i-block4{width: 100%;}
              #subheading-bar .the-sale-text-icon {
                width: 34% !important;
              }
              #subheading-bar .countdown-timer-outer {
                width: 66% !important;
                margin-top: 0 !important;
              }


            }
            .sub-hdr-item {

              height: auto;
            }
            #headwrap .new-hdr-icon {
              background-color: <?php echo $pill_colour; ?> !important;
            }
            #headwrap .new-hdr-icon {
              background-color: <?php echo $pill_colour; ?> !important;
              color: <?php echo $pill_text_colour; ?> !important;
            }

            @media screen and (max-width: 342px){
              #subheading-bar{
                display:none !important;
              }
            }
          </style>
            <?php $background_style = '';
            if(!empty($sitewide_bkg_image))

            {
                $background_style = 'style="background:url(\'/media/banners/'.$sitewide_bkg_image.'\');background-repeat: no-repeat;
    background-size: cover;"';
            }
            ?>

          <div id="subheading-bar" <?php echo  $background_style; ?>>
            <div id="subheading-inner" class="container-ev">
              <div id="sh-i-block1" class="sub-hdr-item">
                <a aria-label="Delivery" href="/help-and-advice/delivery-information">
                  <div class="sh-inner">
                    <div class="sub-hdr-cta-ico sub-hdr-del-ico"><i class="sub-hdr-delivery-ico"></i></div>
                    <div class="sub-hdr-right">
                      <div class="sub-hdr-hdr-text">Free Shipping</div>
                      <div class="sub-hdr-text">Available to UK Mainland*</div>
                    </div>
                  </div>
                </a>
              </div>
              <div id="sh-i-block2" class="sub-hdr-item hidden-xs">
                <a aria-label="Manufacturers Guarantee" href="/manufacturers-guarantee">
                  <div class="sh-inner">
                    <div class="sub-hdr-cta-ico sub-hdr-manu-ico"><i class="sub-hdr-rosette-ico"></i></div>
                    <div class="sub-hdr-right">
                      <div class="sub-hdr-hdr-text">Manufacturer's Guarantee</div>
                      <div class="sub-hdr-text">5 Years for Total Peace of Mind</div>
                    </div>
                  </div>
                </a>
              </div>
              <div id="sh-i-block3" class="sub-hdr-item hidden-xs">
                <a aria-label="Customer Reviews" href="/customer-reviews">
                  <div class="sh-inner">
                    <div class="sub-hdr-cta-ico sub-hdr-trophy-ico"><i class="sub-hdr-award-ico"></i></div>
                    <div class="sub-hdr-right">
                      <div class="sub-hdr-hdr-feefo"></div>
                      <div class="sub-hdr-text">Rated Excellent - <strong>4552</strong> <span class="hidden-md"> Customer </span>Reviews</div>
                    </div>
                  </div>
                </a>
              </div>
              <div id="sh-i-block4" class="sub-hdr-item " style="">

                  <?php

                  $sitewide_custom_block = '
                    
                    
                 
<div style="
    display: flex;
    height: 100%;
    padding: 0;
    margin: 0;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    align-items: center;
    justify-content: center;
">
<div style="height: 100%;width: 50%;display: block;">
<img id="promo_img" src="/media/wysiwyg/xjansale2_v2.png.pagespeed.ic.QrszUdYn1S.webp" alt="" data-pagespeed-url-hash="968517928" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
</div><div style="    display: block;
    width: 40%;
    margin-left: 5%;">
<div id="promo_no"><strong>NOW ON</strong></div>
<div id="promo_wsl">Whilst Stocks Last!</div>
</div>
</div>

                    
                    ';

                  if(!empty($sitewide_custom_block)){
                      // if(Mage::helper('cms/block')->isActive('identifier',$sitewide_custom_block)){
                      //do that

                      //  echo $this->getLayout()->createBlock('cms/block')->setBlockId($sitewide_custom_block)->toHtml();

                      //  }
                      echo $sitewide_custom_block;
                  }
                  else{



                      ?>
                    <a aria-label="Clearance" href="/<?php echo $sitewide_link; ?>">

                      <div id="headwrap">
                        <div class="slider-wrap" style="margin-bottom:10px;">
                          <div class="elements">
                            <div class="inner-elements">
                              <div class="the-sale-text-icon" style="
    color: white;
">
                                <div style="
    font-size: 16px;
"><?php echo $main_text; ?></div>
                                <div class="new-hdr-icon" style="
    display: inline-block;
    width: auto !important;
"><?php echo $pill_text; ?></div>
                              </div>
                              <div class="countdown-timer-outer">
                                <ul id="countdown_timer">
                                  <li><span class="days">&nbsp;</span>
                                    <p>Days</p></li>
                                  <li><span class="hours">&nbsp;</span>
                                    <p>Hours</p></li>
                                  <li><span class="minutes">&nbsp;</span>
                                    <p>Minutes</p></li>
                                  <li><span class="seconds">&nbsp;</span>
                                    <p>Seconds</p></li>
                                </ul>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                      <?php
                  }
                  ?>

              </div>
            </div>
          </div>

            <?

            if ($global_promotion_countdown_pp_enable) {
                $global_promo_this_product = 1;
                ?>
              <div id="headwrap" style="display:none;">
                <div class="slider-wrap" style="margin-bottom:10px;">
                  <div class="elements">
                    <div class="inner-elements">
                      <div class="the-sale-text-icon">

                        <img src="/media/banners/<?php echo $global_promotion_countdown_banner_image; ?>"/>
                      </div>
                      <div class="countdown-timer-outer">
                        <ul id="countdown_timer">
                          <li><span class="days">0</span>
                            <p>Days</p></li>
                          <li><span class="hours">0</span>
                            <p>Hours</p></li>
                          <li><span class="minutes">0</span>
                            <p>Minutes</p></li>
                          <li><span class="seconds">0</span>
                            <p>Seconds</p></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
                <?php
            }

        }


    }
    else{
        if (!empty($global_promotion_override_usp) && $global_promotion_enabled && 1==2) {
            // echo $global_promotion_override_usp;
        } else if (!empty($global_promotion_override_usp_custom) && 1==2 ) {

            //echo $global_promotion_override_usp_custom;

        } else {

        }


    }
}
